 # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: an,knew,had,saw,bought

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
